import { describe, expect, it } from "vitest";
import { musicTrackInputSchema } from "@/lib/garden-validation";

const storedName = "4d6f8365-77d8-4b6d-911d-0e83d0e7c2b1.mp3";

function uploadedTrack(audioUrl: string) {
  return {
    sourceType: "UPLOAD",
    title: "R7 test track",
    audioUrl,
    originalName: "r7-test.mp3",
    storedName,
    mimeType: "audio/mpeg",
    size: 128,
  };
}

describe("music track upload validation", () => {
  it("accepts the canonical music storage URL generated by the uploader", () => {
    const audioUrl = `/uploads/music/2026/07/${storedName}`;
    expect(musicTrackInputSchema.parse(uploadedTrack(audioUrl)).audioUrl).toBe(
      audioUrl,
    );
  });

  it("keeps legacy audio storage URLs compatible", () => {
    const audioUrl = `/uploads/audio/2026/07/${storedName}`;
    expect(musicTrackInputSchema.parse(uploadedTrack(audioUrl)).audioUrl).toBe(
      audioUrl,
    );
  });

  it("rejects paths outside the two dedicated audio directories", () => {
    expect(() =>
      musicTrackInputSchema.parse(
        uploadedTrack(`/uploads/images/2026/07/${storedName}`),
      ),
    ).toThrow();
  });
});
